/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{html,js}",
    "./lib/**/*.{html,js}",
  ],
  theme: {
    extend: {
      colors: {
        'brand-orange': '#ff6900',
        'brand-orange-dark': '#f54900',
        'brand-orange-light': '#ff8904',
        'brand-dark': '#191919',
        'text-muted': '#a1a1a1',
        'text-muted-dark': '#6b6b6b',
        'border-subtle': 'rgba(255, 255, 255, 0.1)',
        'border-subtle-dark': 'rgba(255, 255, 255, 0.05)',
        'bg-overlay': 'rgba(0, 0, 0, 0.4)',
        'bg-status': 'rgba(245, 73, 0, 0.2)',
        'bg-status-border': 'rgba(245, 73, 0, 0.3)',
      },
      spacing: {
        '44': '176px', // rounded from 180px
        'logo-h': '55px',
        'logo-w': '199px',
        'section-gap': '120px',
        '13': '52px',
        '15': '60px',
        '17': '68px',
        '23': '92px',
        '30': '120px',
        '55': '220px',
        '70': '280px',
        '84': '336px',
        '86': '344px',
        '275': '1100px',
      },
      fontSize: {
        'hero': ['130px', { lineHeight: '130px', letterSpacing: '-1.3px' }],
        'hero-mobile': ['56px', { lineHeight: '60px', letterSpacing: '-0.5px' }],
        'display': ['96px', { lineHeight: '86.4px', letterSpacing: '-0.05em' }],
        'display-mobile': ['40px', { lineHeight: '44px', letterSpacing: '-0.02em' }],
        'heading-1': ['48px', { lineHeight: '48px', letterSpacing: '-0.02em' }],
        'heading-1-mobile': ['28px', { lineHeight: '32px', letterSpacing: '-0.01em' }],
        'heading-2': ['32px', { lineHeight: '32px', letterSpacing: '0.01em' }],
        'heading-2-mobile': ['22px', { lineHeight: '26px', letterSpacing: '0' }],
        'heading-3': ['24px', { lineHeight: '24px' }],
        'heading-3-mobile': ['18px', { lineHeight: '22px' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.02em' }],
        'body-lg-mobile': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em' }],
        'body': ['16px', { lineHeight: '23px' }],
        'body-mobile': ['14px', { lineHeight: '20px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'body-sm-mobile': ['12px', { lineHeight: '18px' }],
        'label': ['12px', { lineHeight: '16px', letterSpacing: '0.12em' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.12em' }],
      },
      maxWidth: {
        'container-content': '1100px',
        'container-wide': '1425px',
        'mobile': '390px',
      },
      screens: {
        'mobile': {'max': '390px'},
        'md': '391px',
      },
      borderRadius: {
        'card': '32px',
        'card-sm': '20px',
      },
      lineHeight: {
        'hero': '130px',
        'hero-mobile': '60px',
        'display': '86.4px',
        'display-mobile': '44px',
        'heading-1': '48px',
        'heading-1-mobile': '32px',
        'heading-2': '32px',
        'heading-2-mobile': '26px',
        'heading-3': '24px',
        'heading-3-mobile': '22px',
        'body-lg': '29.25px',
        'body-lg-mobile': '24px',
        'body': '23px',
        'body-mobile': '20px',
        'body-sm': '22.75px',
        'body-sm-mobile': '18px',
        'label': '16px',
        '7': '28px',
        '9': '36px',
        '10': '40px',
        '3xl': '36px',
        '5xl': '48px',
      },
      letterSpacing: {
        'tight': '-0.02em',
        'tighter': '-0.05em',
        'wide': '0.12em',
        'hero': '-1.3px',
      },
    },
  },
  plugins: [],
}
